<?php

namespace ContainerI2afxkY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_GLJSJsHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.GLJSJsH' shared service.
     *
     * @return \App\Repository\JobCreationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\MailController::mailConfirmationEmployer()": the $jobCreationRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\JobCreationRepository".');
    }
}
