<?php

namespace ContainerI2afxkY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostJobControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PostJobController' shared autowired service.
     *
     * @return \App\Controller\PostJobController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PostJobController.php';

        $container->services['App\\Controller\\PostJobController'] = $instance = new \App\Controller\PostJobController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\PostJobController', $container));

        return $instance;
    }
}
