<?php

namespace ContainerVxYJhhw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B4l3PbGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b4l3PbG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b4l3PbG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jobSubscriptionRepository' => ['privates', 'App\\Repository\\JobSubscriptionRepository', 'getJobSubscriptionRepositoryService', true],
        ], [
            'jobSubscriptionRepository' => 'App\\Repository\\JobSubscriptionRepository',
        ]);
    }
}
