<?php

namespace ContainerVxYJhhw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GZBc6NnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gZBc6Nn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gZBc6Nn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jobCreationRepository' => ['privates', '.errored.GLJSJsH', NULL, 'Cannot determine controller argument for "App\\Controller\\MailController::mailConfirmationEmployer()": the $jobCreationRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\JobCreationRepository".'],
            'jobDetailRepository' => ['privates', 'App\\Repository\\JobPostRepository', 'getJobPostRepositoryService', true],
        ], [
            'jobCreationRepository' => '?',
            'jobDetailRepository' => 'App\\Repository\\JobPostRepository',
        ]);
    }
}
