index:
    path: /index
    controller: App\Controller\IndexController::index
index2:
    path: /
    controller: App\Controller\IndexController::index
create:
    path: /create
    controller: App\Controller\EmployerController::create
trial:
    path: /trial
    controller: App\Controller\EmployerController::trial
detail:
    path: /detail
    controller: App\Controller\ExpertController::detail
search:
    path: /search
    controller: App\Controller\ExpertController::search
subscribe:
    path: /subscribe
    controller: App\Controller\ExpertController::subscribe
job:
    path: /job
    controller: App\Controller\EmployerController:job
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }