index:
    path: /index
    controller: App\Controller\IndexController::index
postJob:
    path: /post-job
    controller: App\Controller\PostJobController::postJob
detail:
    path: /detail
    controller: App\Controller\ExpertController::detail
mailConfirmationWorker:
    path: /mail-confirmation-worker
    controller: App\Controller\MailController::mailConfirmationWorker
trial:
    path: /trial
    controller: App\Controller\EmployerController::trial
mailConfirmationEmployer:
    path: /mail-confirmation-employer
    controller: App\Controller\MailController::mailConfirmationEmployer