<?php

namespace ContainerWSfW82d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ARKlkGwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ARKlkGw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ARKlkGw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jobCreationRepository' => ['privates', 'App\\Repository\\JobCreationRepository', 'getJobCreationRepositoryService', true],
            'jobDetailRepository' => ['privates', 'App\\Repository\\JobPostRepository', 'getJobPostRepositoryService', true],
        ], [
            'jobCreationRepository' => 'App\\Repository\\JobCreationRepository',
            'jobDetailRepository' => 'App\\Repository\\JobPostRepository',
        ]);
    }
}
