<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNLt4aXT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNLt4aXT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNLt4aXT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNLt4aXT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNLt4aXT\App_KernelDevDebugContainer([
    'container.build_hash' => 'NLt4aXT',
    'container.build_id' => 'e9210e4f',
    'container.build_time' => 1681306846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNLt4aXT');
