<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDVxKLxe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDVxKLxe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDVxKLxe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDVxKLxe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDVxKLxe\App_KernelDevDebugContainer([
    'container.build_hash' => 'DVxKLxe',
    'container.build_id' => '480ef9f1',
    'container.build_time' => 1681478710,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDVxKLxe');
