<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWSfW82d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWSfW82d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWSfW82d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWSfW82d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWSfW82d\App_KernelDevDebugContainer([
    'container.build_hash' => 'WSfW82d',
    'container.build_id' => '488de338',
    'container.build_time' => 1681337395,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWSfW82d');
